CREATE TABLE USERS(USERNAME VARCHAR(50) NOT NULL PRIMARY KEY,PASSWORD VARCHAR(500) NOT NULL,ENABLED BOOLEAN NOT NULL);

CREATE TABLE AUTHORITIES (USERNAME VARCHAR(50) NOT NULL,AUTHORITY VARCHAR(50) NOT NULL,CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME));
CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (USERNAME,AUTHORITY);

CREATE TABLE GROUPS (
                ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                GROUP_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE GROUP_AUTHORITIES (
                                   GROUP_ID BIGINT NOT NULL,
                                   AUTHORITY VARCHAR(50) NOT NULL,
                                   CONSTRAINT FK_GROUP_AUTHORITIES_GROUP FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(ID)
);

CREATE TABLE GROUP_MEMBERS (
                    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                    USERNAME VARCHAR(50) NOT NULL,
                    GROUP_ID BIGINT NOT NULL,
                    CONSTRAINT FK_GROUP_MEMBERS_GROUP FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(ID)
);

CREATE TABLE PERSISTENT_LOGINS (
                    USERNAME VARCHAR(64) NOT NULL,
                    SERIES VARCHAR(64) PRIMARY KEY,
                    TOKEN VARCHAR(64) NOT NULL,
                    LAST_USED TIMESTAMP NOT NULL
);

CREATE TABLE ACL_SID (
                         ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                         PRINCIPAL BOOLEAN NOT NULL,
                         SID VARCHAR(100) NOT NULL,
                         UNIQUE KEY UNIQUE_ACL_SID (SID, PRINCIPAL)
) ENGINE=INNODB;

CREATE TABLE ACL_CLASS (
                           ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                           CLASS VARCHAR(100) NOT NULL,
                           UNIQUE KEY UK_ACL_CLASS (CLASS)
) ENGINE=INNODB;

CREATE TABLE ACL_OBJECT_IDENTITY (
                                     ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                                     OBJECT_ID_CLASS BIGINT UNSIGNED NOT NULL,
                                     OBJECT_ID_IDENTITY VARCHAR(36) NOT NULL,
                                     PARENT_OBJECT BIGINT UNSIGNED,
                                     OWNER_SID BIGINT UNSIGNED,
                                     ENTRIES_INHERITING BOOLEAN NOT NULL,
                                     UNIQUE KEY UK_ACL_OBJECT_IDENTITY (OBJECT_ID_CLASS, OBJECT_ID_IDENTITY),
                                     CONSTRAINT FK_ACL_OBJECT_IDENTITY_PARENT FOREIGN KEY (PARENT_OBJECT) REFERENCES ACL_OBJECT_IDENTITY (ID),
                                     CONSTRAINT FK_ACL_OBJECT_IDENTITY_CLASS FOREIGN KEY (OBJECT_ID_CLASS) REFERENCES ACL_CLASS (ID),
                                     CONSTRAINT FK_ACL_OBJECT_IDENTITY_OWNER FOREIGN KEY (OWNER_SID) REFERENCES ACL_SID (ID)
) ENGINE=INNODB;

CREATE TABLE ACL_ENTRY (
                           ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                           ACL_OBJECT_IDENTITY BIGINT UNSIGNED NOT NULL,
                           ACE_ORDER INTEGER NOT NULL,
                           SID BIGINT UNSIGNED NOT NULL,
                           MASK INTEGER UNSIGNED NOT NULL,
                           GRANTING BOOLEAN NOT NULL,
                           AUDIT_SUCCESS BOOLEAN NOT NULL,
                           AUDIT_FAILURE BOOLEAN NOT NULL,
                           UNIQUE KEY UNIQUE_ACL_ENTRY (ACL_OBJECT_IDENTITY, ACE_ORDER),
                           CONSTRAINT FK_ACL_ENTRY_OBJECT FOREIGN KEY (ACL_OBJECT_IDENTITY) REFERENCES ACL_OBJECT_IDENTITY (ID),
                           CONSTRAINT FK_ACL_ENTRY_ACL FOREIGN KEY (SID) REFERENCES ACL_SID (ID)
) ENGINE=INNODB;